feat: Add ability to make generic function calls
near/ui.multisafe pull request #114
Opened 2022-06-20 20:15 UTC by Patrick1904

Reference: https://github.com/near/ui.multisafe/issues/94

This PR adds ability to call generic function calls from the multisafe UI:

<img width="883" alt="Screen Shot 2022-06-20 at 4 13 08 PM" src="https://user-images.githubusercontent.com/24921205/174672055-9e9667ac-8054-4352-bb41-379e15950a77.png">

To test:
1. On the left-side panel, click on 'New Transaction'
2. Select 'Make Function Call'
3. Enter the form
4. Submit

2022-06-20 20:18 UTC, agileurbanite requested changes

2022-06-20 20:18 UTC, agileurbanite commented on src/ui/components/Main/MultiSafe/Sidebar/Actions/NewTransaction/MakeFunctionCall/arguments/Arguments.jsx
> +  <TextField
@Patrick1904 nit: can we make this a text area?

2022-06-21 14:23 UTC, judith-Near commented on src/store/multisafe/thunks/onMakeFunctionCall.js
> +            gas: tGas.toString(),
`const ADD_REQUEST_AND_CONFIRM_GAS = new BN('40000000000000');`
this is 40 tGas

but if a user inputs 300 tGas into the form (the form says it's in tGas), it's only equal to BN('300') in reality

2022-06-21 14:26 UTC, judith-Near requested changes
PR lgtm! the only thing that needs to be addressed is the text area for arguments, and the tGas/gas discrepancy

2022-06-21 16:29 UTC, Patrick1904 commented on src/store/multisafe/thunks/onMakeFunctionCall.js
> +            gas: tGas.toString(),
Great catch!

2022-06-21 16:29 UTC, Patrick1904 commented on src/ui/components/Main/MultiSafe/Sidebar/Actions/NewTransaction/MakeFunctionCall/arguments/Arguments.jsx
> +  <TextField
Good one!

2022-06-21 16:30 UTC, judith-Near submitted a review, later dismissed
lgtm!

2022-06-21 20:52 UTC, judith-Near submitted a review, later dismissed

2022-06-21 22:39 UTC, agileurbanite submitted a review, later dismissed
LGTM

2022-06-22 15:36 UTC, judith-Near commented on src/store/multisafe/thunks/onMakeFunctionCall.js
> +const signTxByLedger = async (
nit: can we destructure the args for this object, it's a bit large

2022-06-22 15:37 UTC, judith-Near approved these changes

2022-06-22 15:44 UTC, judith-Near approved these changes

2022-06-22 15:45 UTC, merged