[WIP] Integrating with wallet-selector
near/ui.multisafe pull request #134
Opened 2022-07-06 04:33 UTC by hcho112

(Do not merge it yet, there are still more work need to be done)

This PR contains implementations/changes to support integrating wallet-selector into multisafe. 

First of all, my apologies for making a big PR. Initially I have under estimated the scope of the work and I decided to stop when I reach to a point all the transactions functional and ready to be used.

The value of integrating with wallet-selector is that we let `wallet-selector` to drive the authentication and use the API provided to handle the transactions. (eg. `signAndSendTransaction`)

Currently it will display to support 3 wallets, `near-wallet`, `my-near-wallet` and `ledger`. (FYI, wallet-selector deprecates the use of `near-wallet`. )

I have introduced the `useWalletSelector` hook to retrieve `wallet-selector` related data anywhere in the application. 

Prior to merge this PR, these things need to be confirmed:

- [ ] Make sure existing authenticated users get logged out properly (Need to test this by branch off to master -> authenticate -> checkout to MUL-10 -> refresh the page)

- [ ] Test on transferring the NFT tokens. (Currently transfer transaction returns success on explorer but actual transfer doesn't happen. Same behaviour found on testnet)

- [ ] Major end-to-end testing to make sure everything works correctly. (With another engineer)

2022-07-10 22:55 UTC, hcho112 commented
Confirmed that NFT transfer is working

2022-07-13 17:48 UTC, judith-Near commented
`Make sure existing authenticated users get logged out properly (Need to test this by branch off to master -> authenticate -> checkout to MUL-10 -> refresh the page)`
Just tested this, they do not get logged out. They stay logged in with the stale wallet account management mechanism, and functionality such as transferring funds results in `Uncaught (in promise) Error: No wallet selected`

2022-07-14 02:36 UTC, hcho112 commented
Pushed fix for @judith-Near's feedback

2022-07-14 18:13 UTC, judith-Near commented
`Unhandled Rejection (Error): Wrong connection type, must be 'rpc_near-wallet', 'rpc_ledger' or 'archival-rpc_read-only', got 'rpc_undefined' instead` from src/store/multisafe/onEditMultisafe.js:195
steps to repro: edit multisafe member by removing one/adding one

2022-07-15 03:56 UTC, hcho112 commented
@judith-Near thank you for thoughtful QA/testing. I believe majority of the bugs were introduced during rebasing the master (Since there was a big [change merged to master ](https://github.com/near/ui.multisafe/pull/132), I had to rebase and most of the bugs you have raise occurred after, regardless I should have done a final check/test, my apologies)

I was able to replicate the logout issue, onEditMultisafe issue but logout seems to work just fine at the moment.
If possible I would like to discuss rollback with @agileurbanite as well.

2022-07-17 23:50 UTC, hcho112 commented
Created [PR-136](https://github.com/near/ui.multisafe/pull/136) dedicated for rollback purpose. PR-136 must be merged first  prior to merging current PR.

2022-07-21 16:43 UTC, marcinbodnar requested changes
Great job Danny, it is a challenging task.

Few comments in the code, and also I noticed:
 - on Firefox we have only 2 wallet options visible
 - after disconnecting, `multisafe/multi-marcin-1.multisafe.testnet/dashboard` is making redirect but `multisafe/multi-marcin-1.multisafe.testnet/edit-safe` is trying to load data
 - similar with removing a safe, when you remove the safe you can still enter safe URLs and it's trying to load data, without success.

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/EditMultisafe/Form/FormConfirmations.jsx
> +// import { useEffect } from 'react';
This file is not used anymore. Probably added while rebasing.

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/EditMultisafe/Form/FormDisconnect.jsx
> +        onDisconnect({ history, selector });
no `await`?

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/EditMultisafe/Form/FormMembers.jsx
> +import { yupResolver } from '@hookform/resolvers/yup';
This file is not used anymore. Probably added while rebasing.

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/EditMultisafe/Form/FormRemove.jsx
> +        onDisconnect({ history, selector });
no `await`?

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/MultiSafe.jsx
> +                        near && (
I wonder, why we don't want to handle any routes if `state.general.entities.near`? 

Generally, it seems a bit odd because the logic seems to say that we don't want to show any routes if `near` is underlined, but at the same time we are showing `sidebar` etc. I wonder is it possible to refactor it, and handle `!near` earlier in the logic? It seems like it should be happening before `MultiSafe` component is rendering, but it's possible that I'm missing context here.

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/general/Topbar/Account/Modal/Modal.jsx
> +        onDisconnect({ history, selector });
no `await`?

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/general/Topbar/NonConnected/NonConnected.jsx
> +        onDisconnect({ history, selector });
no `await`?

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Main/general/Topbar/Topbar.jsx
> +        updateAccountId({ selector, setAccountId, selectedWalletId });
Do we still want to render `Topbar` component if `if (!selector || !selectedWalletId) return null;`?

2022-07-21 16:43 UTC, marcinbodnar commented on src/ui/components/Welcome/Welcome.jsx
> +    useEffect(() => {
I wonder if this is the right place for this code. It seems like if we want to push to `/get-started` it should be done before the `Welcome` component is rendering.

2022-07-21 21:55 UTC, hcho112 commented
@marcinbodnar thank you for thoughtful review, will continue review/update/comment on your feedback. Meanwhile I also discovered that `wallet-selector` officially doesn't support `ledger` so left a [issue](https://github.com/near/wallet-selector/issues/361) on their repo.

2022-07-21 22:42 UTC, hcho112 commented
@marcinbodnar  `after disconnecting, multisafe/multi-marcin-1.multisafe.testnet/dashboard is making redirect but multisafe/multi-marcin-1.multisafe.testnet/edit-safe is trying to load data`

I believe this is existing bug, which can be replicated on `testnet.multisafe.io` as below:
<img width="2343" alt="image" src="https://user-images.githubusercontent.com/6027014/180326508-ce83b9ce-8ca6-4f02-905c-4e1c567934b2.png">

After further investigation I was able to resolved it by updating `safeEdit` routes on `manageNavigation`. 
(I believe `safeEdit` route is introduced by [your commit ](https://github.com/near/ui.multisafe/commit/8c365f74869531920aba61436f03350f81d1acce) ) 

Regardless, since I was able to resolve it, I will also include them in my PR

2022-07-22 01:33 UTC, hcho112 commented on src/store/multisafe/helpers/getMultisafeContract.js
> +    const account = ((walletType === 'my-near-wallet' || walletType === 'near-wallet') && wallet)
With new change, no. `walletType` will be referenced by `wallet-selector`.

2022-07-22 01:39 UTC, hcho112 commented on src/ui/providers/WalletSelectorProvider/WalletSelectorProvider.jsx
> +const WalletSelectorContext = React.createContext(null);
First of all, we should NOT use redux to store selector. [link](https://redux.js.org/understanding/thinking-in-redux/three-principles) We should only store `pure functions` in reducer in general. (pure array, pure object etc)

I do notice that we already do store non-pure data types on reducer but moving forward, we should avoid doing it so. 

Secondly, `useContext`  to create a `provider` approach is considered as good modern practice to access data without passing props on layers of components.

Lastly, I got this motive from going over react example on `wallet-selector` which I do believe is right way to do so.

2022-07-22 01:44 UTC, hcho112 commented on src/store/multisafe/thunks/onConfirmRequest.js
> +        case 'near-wallet':
From my perspective, it is not ideal to do a wallet-selector integration/migration AND doing the abstraction. It is a risky process. (specially without any tests) Furthermore, in multisafe, we do have many actions/services that has tailored implementation on specific to either `near-wallet` or `ledger` so I had to apply switch on thunks so make sure when another dev introduce a new wallet, they will have to update on these switch cases.

2022-07-22 01:46 UTC, hcho112 commented on src/store/multisafe/thunks/onConfirmRequest.js
> +            throw Error(`Unsupported wallet selected: '${selectedWalletId}'`);
Continue from previous comment, I rather find this approach helpful for a developer to introduce a new wallet in the future. When they update the code to introduce a new wallet in multisafe, they can go over actions/services and test to see if functionality is implemented properly one by one.

2022-07-22 03:58 UTC, hcho112 commented on src/ui/components/Main/general/Topbar/Topbar.jsx
> +        updateAccountId({ selector, setAccountId, selectedWalletId });
Yes, since it does more than just `selector` base activity, (eg, showing loading animation) lets leave it as it is

2022-07-22 19:33 UTC, judith-Near commented
batch request of editing member + editing number of confirmations lead to the following error
<img width="1036" alt="Screen Shot 2022-07-22 at 3 28 28 PM" src="https://user-images.githubusercontent.com/103452915/180514486-2103a6b5-2466-4bb1-9919-58cd18a00a1c.png">

2022-07-25 01:33 UTC, hcho112 commented
@judith-Near thank you for spotting the error. It was related to recent change update on batch request. I have pushed the fix. 
@marcinbodnar is it possible if you could test batch request in this PR? (and also re-review the changes please)

2022-07-25 06:03 UTC, roshaans commented on src/ui/components/Main/MultiSafe/Sidebar/Actions/NewTransaction/MakeFunctionCall/MakeFunctionCall.jsx
>  import { makeFunctionCallSchema } from '../../../../../../../../utils/validation/makeFunctionCallModal';
It would help general readability if the import statement read

`import { makeFunctionCallSchema } from '@utils/validation/makeFunctionCallModal';`

Coming up with aliases for common paths accessed throughout the app will help us reason through code better and avoid 'import hell' while also forcing us to reason through the most proper places to put our code. 

What do you think about having aliases for the following folders inside of `src/` -> `@store/`, `@ui/`, `@near/`, `@config/`, `@utils/`.

2022-07-25 21:41 UTC, marcinbodnar requested changes

2022-07-25 21:41 UTC, marcinbodnar commented on src/ui/providers/WalletSelectorProvider/WalletSelectorProvider.jsx
> +const WalletSelectorContext = React.createContext(null);
> First of all, we should NOT use redux to store selector. link We should only store pure functions in reducer in general. (pure array, pure object etc)

Yes, I'm aware. That's not what I meant, but probably my comment lacked proper description :)

What I mean is that we can use redux to store data (only data) instead of passing it using context, and implement the `selector` without using context.

Right now we are using Context to:
1. Pass static data: `accounts`, `accountId`, `selectedWalletId` that we can easily store in redux, and have access to at any time.
2. Pass `selector` function to the components, which is actually don't used by components, because it's passed to the thunks. So we are using context to pass `selector` to the component, which is actually don't used in components.

As you wrote, Context is a good solution, when passing data to the components - but mostly if you don't use any state management. We have redux, and we don't need to pass data with Context - it's always available from the redux state.

The example that you mentioned, from `wallet-selector` repo, uses Context, which is a good solution when you don't want to play with redux configuration just to pass a few data.

I'm happy to discuss it with you and propose a specific solution. But it can be addressed as a separate PR, not to block this PR - because it's not a bug.

2022-07-25 21:52 UTC, marcinbodnar commented
> @judith-Near thank you for spotting the error. It was related to recent change update on batch request. I have pushed the fix. @marcinbodnar is it possible if you could test batch request in this PR? (and also re-review the changes please)

@hcho112 Tested batch request. Everything seems to be working well.

2022-07-25 21:59 UTC, hcho112 commented on src/ui/components/Main/MultiSafe/Sidebar/Actions/NewTransaction/MakeFunctionCall/MakeFunctionCall.jsx
>  import { makeFunctionCallSchema } from '../../../../../../../../utils/validation/makeFunctionCallModal';
Thank you for valuable review @roshaans . However as this PR is continue to grow, I would like to focus on `wallet-selector` specific implementation. (At this stage, I would like to focus on any potential bug introduced or lack of feature related to wallet-selector that should be included)

To keep the track of the, I have created a[ new issue ](https://github.com/near/ui.multisafe/issues/143) so that we can carry on working on this later.

2022-07-26 01:58 UTC, hcho112 commented
It looks like I couldn't reply to each comment directly (I think comment link got lost during the rebase, so I will respond to your comments here)
https://github.com/near/ui.multisafe/pull/134#discussion_r929255109
It actually does execute `signTxByNearWallet` function.

2022-07-26 02:03 UTC, hcho112 commented
https://github.com/near/ui.multisafe/pull/134#discussion_r929261497
For this one, the intention of not blocking early is because we want to prompt error message when **developer** trying to introduce a new wallet. (As they work on step by step, if some thunk doesn't work, it needs a way to feedback to them saying "hey you missed this". ) Based on new `wallet-selector` paradigm, there is no way that end user can pick/choose/select non supported wallet.

I'm happy to replace the error message to something like `Unhandled walletType inserted, please update the case statement` (Or happy to get recommendation from you)

2022-07-26 02:35 UTC, hcho112 commented
https://github.com/near/ui.multisafe/pull/134#discussion_r929326215
Thank you for your feedback, and yes I do agree actually.
Initially, I wanted to move away/decouple the legacy implementation from new wallet-selector via introducing the context provider. However, during the work/feedback I already put enough effort in a way that it stably loads data from wallet selector, so at the entry point, I can load the key metrics to redux store. (However some parts need to be stay as it is, due to accessing `signAndSendTransaction` function from `wallet` instance.)

As you said, I will do a follow up PR after this one.

2022-07-26 20:57 UTC, marcinbodnar submitted a review, later dismissed
Thanks @hcho112

2022-08-02 17:42 UTC, marcinbodnar approved these changes

2022-08-02 21:49 UTC, merged