Safely rollback pre wallet-selector state
near/ui.multisafe pull request #136
Opened 2022-07-17 23:39 UTC by hcho112

This PR contains implementation to safely rollback wallet-selector integration (https://github.com/near/ui.multisafe/pull/134)

This PR also has no effect on existing `near-wallet` and `ledger` login process. 

This PR need to be merged prior to [wallet-selector integration](https://github.com/near/ui.multisafe/pull/134)

2022-07-27 19:49 UTC, marcinbodnar requested changes

2022-07-27 19:49 UTC, marcinbodnar commented on src/store/general/thunks/onInitApp/onInitApp.js
> +    if (authKey || !(walletType === 'near-wallet' || walletType === 'ledger')) {
I don't think it's working properly.

If you combine these two sets of changes (#134 and #136) you will see two issues:
1. If you try to login to an existing wallet, it's throwing an error, and you are not able to login to safe.
2. If you are already logged in (you can do it by removing part of the code from #136 while logging in) and you refresh the page, you are disconnected instantly.

The problem is with this condition:
```js
// if wallet-selector authKey found or unsupported wallet is selected, disconnect
if (authKey || !(walletType === 'near-wallet' || walletType === 'ledger')) {
```
that is saying that the user should be disconnected if `authKey` exists and `walletType` is different than `near-wallet/ledger`.

2022-07-28 22:01 UTC, hcho112 commented on src/store/general/thunks/onInitApp/onInitApp.js
> +    if (authKey || !(walletType === 'near-wallet' || walletType === 'ledger')) {
can we have a chat on this? when I test them everything work just fine. 
for `If you are already logged in (you can do it by removing part of the code from https://github.com/near/ui.multisafe/pull/136 while logging in) and you refresh the page, you are disconnected instantly.` this is intentional change. The way `wallet-selector` works is very different to existing implementation that requires auto-logout to make a fresh start.

2022-08-01 20:31 UTC, marcinbodnar approved these changes

2022-08-01 23:22 UTC, merged