bug-fix: View In Explorer Link does not work for pending actions
near/ui.multisafe pull request #142
Opened 2022-07-25 19:30 UTC by roshaans

In the Recipient column, the view in explorer link does not work unless the action has been completed and a transaction hash exists on chain. 

If the multisafe action is pending, we should either remove the link to see the action tx in the explorer (as it does not yet exist) or show the user the account in the explorer. 

### **BEFORE**
![err_ui_safe](https://user-images.githubusercontent.com/25015977/180854682-cb20fdee-30dc-4966-a628-b8e75ced9d8b.gif)

### **AFTER**
![err_fixed_ui](https://user-images.githubusercontent.com/25015977/180858989-3842d642-6a36-4532-86cb-4e0546e38054.gif)

2022-07-26 03:52 UTC, hcho112 commented on src/ui/components/Main/MultiSafe/general/OpenInExplorer/OpenInExplorer.jsx
> +                return config.getCheckAccountInExplorerUrl(accountId);
just one small change, pull out `config.getCheckAccountInExplorerUrl(accountId);` into a constant above and switch statement and use it instead?

2022-07-26 15:49 UTC, roshaans commented on src/ui/components/Main/MultiSafe/general/OpenInExplorer/OpenInExplorer.jsx
> +                return config.getCheckAccountInExplorerUrl(accountId);
Thank you for the feedback! Makes sense to see the internals of that function since it is just string interpolation.

2022-07-26 18:23 UTC, marcinbodnar requested changes
The thing is that it's not really solving the problem. Please check that if you go to the `Requests/Completed` page you will see that the link is redirecting to explorer but to the transaction page (not the account page). 

`if (!transactionHash)` is unnecessary, actually, this component doesn't have an error. The error is in `Reciepuent.jsx` components (both of them) - in this components we are passing 
`type="transaction"` and `transactionHash={transactionHash}` to `OpenInExplorer` which is wrong. Both these props should be removed because we want to link to `account` explorer page. If you remove these props, it solves both problems - changes in `OpenInExplorer.jsx` are not needed.

2022-07-27 14:53 UTC, roshaans commented
> The thing is that it's not really solving the problem. Please check that if you go to the `Requests/Completed` page you will see that the link is redirecting to explorer but to the transaction page (not the account page).

Great point @marcinbodnar! The user expects to go to the Accounts page if they are looking at the recipient column. I think it is also important to give the user the option to see the transaction on the chain, so I will add a link to go to the on-chain transaction in the Status column of the `Requests Completed` page.

2022-07-27 15:02 UTC, marcinbodnar commented
> I think it is also important to give the user the option to see the transaction on the chain

Good idea.

2022-07-27 18:16 UTC, marcinbodnar requested changes

2022-07-27 18:16 UTC, marcinbodnar commented on src/ui/components/Main/MultiSafe/general/OpenInExplorer/OpenInExplorer.jsx
> +    const getTransactionInExplorerUrl = (transactionHash) => `${config.explorerUrl}/transactions/${transactionHash}`;
Why implementing `getAccountInExplorerUrl` and `getTransactionInExplorerUrl`? The same functions are available from `config` and were used before.

2022-07-27 19:44 UTC, roshaans commented on src/ui/components/Main/MultiSafe/general/OpenInExplorer/OpenInExplorer.jsx
> +    const getTransactionInExplorerUrl = (transactionHash) => `${config.explorerUrl}/transactions/${transactionHash}`;
correct. We can keep the functionality the same, I figured a bit of refactoring would help but it leaves redundant code in the config object. Made the changes!

2022-07-28 13:22 UTC, marcinbodnar approved these changes
Good job @roshaans

2022-08-02 15:35 UTC, merged